#!/usr/bin/env python
import os
import sys
import json
from pathlib import Path

from nmt.utils import train_seq2seq


sagemaker_dir = '/opt/ml'
data_dir = os.path.join(sagemaker_dir, 'input/data/training')
output_dir = os.path.join(sagemaker_dir, 'model')
params_path = os.path.join(sagemaker_dir, 'input/config/hyperparameters.json')

DEFAULT_DATA_FILENAME = 'deu.txt'


def main():
    hyper_parameters = {}

    if Path(params_path).is_file():
        with open(params_path, 'r') as f:
            hyper_parameters = json.load(f)

    train_test_split = hyper_parameters.get('train_test_split', 0.2)
    data_filename = hyper_parameters.get('data_filename', DEFAULT_DATA_FILENAME)
    data_path = os.path.join(data_dir, data_filename)

    evaluator = train_seq2seq(data_path, output_dir, train_test_split)
    evaluator.save_artifacts(output_dir)

    # save hyperparameters containing model configuration
    # to be able to properly reconstruct the model
    hyper_parameters_path = os.path.join(output_dir, evaluator.timestamp,
                                         'hyperparameters.json')
    with open(hyper_parameters_path, 'w') as f:
        json.dump(hyper_parameters, f)


if __name__ == '__main__':
    main()

    sys.exit(0)
