#!/usr/bin/env python
import os
import sys
import json
from pathlib import Path
from copy import deepcopy

from nmt.utils import train_seq2seq


sagemaker_dir = '/opt/ml'
data_dir = os.path.join(sagemaker_dir, 'input/data/training')
output_dir = os.path.join(sagemaker_dir, 'model')
params_path = os.path.join(sagemaker_dir, 'input/config/hyperparameters.json')

DEFAULT_DATA_FILENAME = 'deu.txt'


def sanitise_hyper_parameters(hyper_parameters: dict) -> dict:
    sanitised_hyper_parameters = {}

    for key, val in hyper_parameters.items():
        if val.isdigit():
            sanitised_hyper_parameters[key] = int(val)
            continue
        try:
            sanitised_hyper_parameters[key] = float(val)
        except ValueError:
            sanitised_hyper_parameters[key] = val

    return sanitised_hyper_parameters


def main():
    hyper_parameters = {}

    if Path(params_path).is_file():
        with open(params_path, 'r') as f:
            hyper_parameters = json.load(f)

    original_hyper_parameters = deepcopy(hyper_parameters)

    train_test_split = float(hyper_parameters.pop('train_test_split', 0.2))
    data_filename = hyper_parameters.pop('data_filename', DEFAULT_DATA_FILENAME)
    epochs = int(hyper_parameters.pop('epochs', 15))

    data_path = os.path.join(data_dir, data_filename)

    # handle hyperparematers coming from Sagemaker
    hyper_parameters.pop('_tuning_objective_metric', None)
    sanitised_hyper_parameters = sanitise_hyper_parameters(hyper_parameters)

    evaluator = train_seq2seq(data_path, output_dir, train_test_split, epochs,
                              **sanitised_hyper_parameters)

    evaluator.save_artifacts(output_dir)

    # save hyperparameters containing model configuration
    # to be able to properly reconstruct the model
    hyper_parameters_path = os.path.join(output_dir, evaluator.timestamp,
                                         'hyperparameters.json')
    with open(hyper_parameters_path, 'w') as f:
        json.dump(original_hyper_parameters, f)


if __name__ == '__main__':
    main()

    sys.exit(0)
