FROM tensorflow/tensorflow:1.12.0-gpu-py3

COPY ./requirements-gpu.txt /opt/program/
WORKDIR /opt/program

RUN pip install -r requirements-gpu.txt

COPY ./train /opt/program/
COPY ./nmt/ /opt/program/nmt/
COPY ./scripts/ /opt/program/scripts/

ENV PATH="/opt/program:${PATH}"
